# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: static-ip-pool
spec:
  addresses:
  - 192.168.3.250-192.168.3.252
  - 192.168.3.11-192.168.3.17

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: static-advertise
spec: {}