all:
  children:
    # Group k8s_node_init
    k8s_node_init:
      hosts:
        k8s_node:
          # Node variables
          ansible_host: "{{ ansible_host }}"
          ansible_user: "{{ node_ssh_user }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
          ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
          kubeconfig_path: "{{ kubeconfig_path }}"
          kubeconfig_method: "{{ kubeconfig_method }}"
          cluster_name: "{{ cluster_name }}"
          # Configurations to initialize node (init_node.sh)
          k8s_version: "{{ k8s_version }}"
          cri_os: "{{ cri_os }}"
          cri_version: "{{ cri_version }}"
          required_ports: "{{ required_ports }}"
          open_ports_for_master_or_worker: "{{ open_ports_for_master_or_worker }}"
          json_hostnames: "{{ json_hostnames }}"
          # To add a new nodes
          new_json_hostnames: "{{ new_json_hostnames }}"
          # Configurations to setup a node (setup_node.sh)
          node_name: "{{ node_name }}"
          node_type: "{{ node_type }}"
          master_type: "{{ master_type }}"
          node_ip: "{{ node_ip }}"
          pod_cidr: "{{ pod_cidr }}"
          # System configurations
          cluster_env: "{{ env }}"
          local_path_git: "{{ local_path_git }}"
          # Haproxy
          haproxy_enabled: "{{ haproxy_enabled }}"
          haproxy_ip: "{{ haproxy_ip }}"
          haproxy_port: "{{ haproxy_port }}"
          haproxy_dns: "{{ haproxy_dns }}"
          haproxy_dns_or_ip: "{{ haproxy_dns_or_ip }}"
          haproxy_dns_provider: "{{ haproxy_dns_provider }}" # Not used at the moment
