apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-hw1
  namespace: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  loadBalancerIP: 192.168.3.252 # Change with your ip
  type: LoadBalancer
