{{- range $container := .Values.containerConfigs }}
  {{- $extraVars := default (list) $container.extraSecretVars }}
  {{- $extraFiles := default (list) $container.extraSecretFiles }}
  {{- range $secret := (concat $extraVars $extraFiles) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $container.name }}-{{ $secret.name }}"
  namespace: {{ $.Values.application.namespace }}
type: Opaque
data:
  {{- range $key, $val := $secret.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
